eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
    hostname: localhost
server:
  error:
    include-message: always
  port: 3020
spring:
  application:
    name: like-service
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: likeDB
      port: 27017
logging:
  file:
    name: C:/Users/savitago/Downloads/like-service/src/logs/like_service.log