eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
server:
  error:
    include-message: always
  port: 3020
spring:
  application:
    name: like-service
  cloud:
    discovery:
      enabled: true
  data:
    mongobd:
      database: likeDB
      port: 27017